# Generated by Django 5.2.6 on 2025-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
